services:
  boot:
    build:
      context: ./boot
      dockerfile: dockerfile
    ports:
      - '8888:8888'
    networks:
      - testnet
    restart: unless-stopped

  webflux:
    build:
      context: ./webflux
      dockerfile: dockerfile
    ports:
      - '7777:7777'
    networks:
      - testnet
    restart: unless-stopped

  node:
    build:
      context: ./node
      dockerfile: dockerfile
    ports:
      - '8787:8787'
    networks:
      - testnet
    restart: unless-stopped

networks:
  testnet:
    driver: bridge