server:
  port: 8888
  tomcat:
    max-connections: 200
    # Tomcat thread pool
    threads:
      min: 2
      max: 4

spring:
  threads:
    virtual:
      enabled: true
  task:
    execution:
      pool:
        core-size: 5 # Doesn't have an effect if virtual threads are enabled.
        queue-capacity: 100 # Doesn't have an effect if virtual threads are enabled.
        max-size: 10 # Doesn't have an effect if virtual threads are enabled.
    simple:
      concurrency-limit: 100 # Default unbounded